# Generated by Django 4.2.2 on 2023-06-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=245)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
